# Generated by Django 4.0.4 on 2022-04-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_kandydat_urzadnajakikandyduje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandydat',
            name='poparcie',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
