# Generated by Django 4.0.4 on 2022-05-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_glosowanie_remove_kandydat_urzadnajakikandyduje_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Glosowanie',
            new_name='Wybory',
        ),
        migrations.RenameField(
            model_name='kandydat',
            old_name='glosowanie',
            new_name='wybory',
        ),
        migrations.RenameField(
            model_name='raport',
            old_name='glosowanie',
            new_name='wybory',
        ),
    ]
