# Generated by Django 4.0.4 on 2022-06-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_kandydat_poparcie_alter_wybory_rodzaj_wyborow'),
    ]

    operations = [
        migrations.AddField(
            model_name='wybory',
            name='oddanych_glosow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wybory',
            name='rodzaj_wyborow',
            field=models.CharField(choices=[('Starosty roku', 'Starosty roku'), ('Parlamentarne', 'Parlamentarne'), ('Dziekana wydziału', 'Dziekana wydziału'), ('Prezydenckie', 'Prezydenckie')], max_length=30),
        ),
    ]
