# Generated by Django 4.0.4 on 2022-06-06 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_wyborca_user_alter_wybory_rodzaj_wyborow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wyborca',
            old_name='czyUprawniony',
            new_name='czy_uprawniony',
        ),
        migrations.RemoveField(
            model_name='wyborca',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='wyborca',
            name='nazwisko',
        ),
        migrations.RemoveField(
            model_name='wyborca',
            name='wiek',
        ),
        migrations.AddField(
            model_name='wyborca',
            name='wybory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.wybory'),
        ),
        migrations.AlterField(
            model_name='wybory',
            name='rodzaj_wyborow',
            field=models.CharField(choices=[('Starosty roku', 'Starosty roku'), ('Prezydenckie', 'Prezydenckie'), ('Parlamentarne', 'Parlamentarne'), ('Dziekana wydziału', 'Dziekana wydziału')], max_length=30),
        ),
    ]
