# Generated by Django 4.0.4 on 2022-06-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_wybory_rodzaj_wyborow'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyborca',
            name='imie',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wyborca',
            name='nazwisko',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wybory',
            name='rodzaj_wyborow',
            field=models.CharField(choices=[('Parlamentarne', 'Parlamentarne'), ('Prezydenckie', 'Prezydenckie'), ('Starosty roku', 'Starosty roku'), ('Dziekana wydziału', 'Dziekana wydziału')], max_length=30),
        ),
    ]
