# Generated by Django 4.0.4 on 2022-06-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_wyborca_imie_wyborca_nazwisko_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandydat',
            name='poparcie',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='wybory',
            name='oddanych_glosow',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='wybory',
            name='rodzaj_wyborow',
            field=models.CharField(choices=[('Parlamentarne', 'Parlamentarne'), ('Dziekana wydziału', 'Dziekana wydziału'), ('Starosty roku', 'Starosty roku'), ('Prezydenckie', 'Prezydenckie')], max_length=30),
        ),
    ]
