# Generated by Django 4.0.4 on 2022-06-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_kandydat_poparcie_alter_wybory_oddanych_glosow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wybory',
            name='rodzaj_wyborow',
            field=models.CharField(choices=[('Dziekana wydziału', 'Dziekana wydziału'), ('Starosty roku', 'Starosty roku'), ('Parlamentarne', 'Parlamentarne'), ('Prezydenckie', 'Prezydenckie')], max_length=30),
        ),
    ]
