# Generated by Django 4.0.4 on 2022-06-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_wybory_rodzaj_wyborow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wybory',
            name='rodzaj_wyborow',
            field=models.CharField(choices=[('Starosty roku', 'Starosty roku'), ('Parlamentarne', 'Parlamentarne'), ('Prezydenckie', 'Prezydenckie'), ('Dziekana wydziału', 'Dziekana wydziału')], max_length=30),
        ),
    ]
