# Generated by Django 4.0.4 on 2022-06-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_wyborca_czy_glosowal_alter_wyborca_czy_uprawniony_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raport',
            name='frekwencja',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='wybory',
            name='rodzaj_wyborow',
            field=models.CharField(choices=[('Starosty roku', 'Starosty roku'), ('Prezydenckie', 'Prezydenckie'), ('Parlamentarne', 'Parlamentarne'), ('Dziekana wydziału', 'Dziekana wydziału')], max_length=30),
        ),
    ]
