# Generated by Django 4.0.4 on 2022-06-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_raport_frekwencja_alter_wybory_rodzaj_wyborow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wybory',
            name='oddanych_glosow',
        ),
        migrations.AlterField(
            model_name='wybory',
            name='rodzaj_wyborow',
            field=models.CharField(choices=[('Prezydenckie', 'Prezydenckie'), ('Dziekana wydziału', 'Dziekana wydziału'), ('Starosty roku', 'Starosty roku'), ('Parlamentarne', 'Parlamentarne')], max_length=30),
        ),
    ]
